### ISSUE TITLE
Sd

### ISSUE THREAD

**Issue by MatiM72737** [trteodor/LVGL_Ported_TO_ILI9341_STM32F407#1]
Witam, zauważyłem, że w konfiguracji .ioc jest skonfigurowane użycie karty sd i fatfs, natomiast, nie widzę żadnego dostępnego przykładu do powiedzmy wyświetlenia obrazka bmp z karty sd, jesteś w stanie pomóc?
teraz jednak widzę, że fatfs jest skonfigurowany jako do obslugi dysku usb, w jaki sposob to przerobić do użycia karty sd i ogolnie wyswietlic z niej obraz bmp?

**Comment by trteodor** [comment]
Cześć Mateusz, 
Kodu za ciebie nie napisze ;)
Niestety z tematem już od dłuższego czasu nie miałem styczności, i niewiele już pamiętam, więc też za wiele nie podpowiem. 
Mogę cię jedynie pocieszyć, że temat jest z pewnościa bardzo prosty i do zrobienia. Kiedyś to robiłem ale bardzo dawno temu.. a jak się czegoś nie używa, nie powtarza, to się zapomina. Musisz szperać po sieci, z pewnością są poradniki jak taki obraz BMP pobrać z karty SD do pamięci RAM, i dalej wyświetlić go na wyświetlaczu.

Przypomniałem sobie jedynie, że przykładem przekazania bufora z pamięci RAM do wyświetlacza jest funkcja:
**ILI9341_flush** w pliku:
https://github.com/trteodor/LVGL_Ported_TO_ILI9341_STM32F407/blob/master/ILI9341/lv_driver.c

**Comment by trteodor** [comment]
Do prostych aplikacji graficznych, w dalszym ciągu, z czystym sumieniem, polecę LVGL Square line. Demonstruje ten GUI designer, nieco szczerzej na tym video:
https://youtu.be/CsGl308vEaE?si=88gW0IkzCCphPSE4

Zastosowanie takiego designera ulatwi ci tworzenie aplikacji graficznej. Nie widzę sensu aby w dzisiejszych czasach, tworzyć aplikacje graficzne od zera w kodzie. Zdecydowanie lepiej skorzystać z jakiegoś generatora kodu
